name: shopapp
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
    sdk: '>=2.19.1 <3.0.0'

dependencies:
    cupertino_icons: ^1.0.2
    flutter:
        sdk: flutter
    flutter_riverpod: ^2.1.3
    freezed_annotation: ^2.2.0
    google_fonts: ^4.0.1
    intl: ^0.18.0
    meta: ^1.8.0

dev_dependencies:
    build_runner: ^2.3.3

    flutter_lints: ^2.0.0
    flutter_test:
        sdk: flutter
    freezed: ^2.3.2

flutter:
    uses-material-design: true
